#!/bin/sh

if [ $# -lt 1 ]
then
	cat <<-tac
		USAGE: $0 <input file>

		Input file should be an LLVM IR or BC file.
	tac
	exit 1
fi

readonly mydir="`dirname "$0"`"
opt-3.7 -load "$mydir/TraceVariables.so" -load "$mydir/GenerateEquations.so" -geneqns -o /dev/null "$@"
